# Generated by Django 5.1.7 on 2025-03-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyexchange",
            name="currency_code",
            field=models.CharField(max_length=3),
        ),
    ]
